const HEADER_HEIGHT = 88;

export const styles = {
  page: {
    minHeight: "100vh",
    background: "var(--primary-color)",
  },
  container: {
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "0 24px",
    display: "flex",
    gap: "32px",
  },
  sidebar: {
    width: "280px",
    height: "fit-content",
    background: "white",
    borderRadius: "16px",
    padding: "24px",
    position: "sticky",
    top: HEADER_HEIGHT + 32,
    display: "flex",
    flexDirection: "column",
    gap: "24px",
    boxShadow: "0 4px 6px -1px rgba(0,0,0,0.1)",
  },
  profileSection: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "16px",
    padding: "16px 0",
    borderBottom: "1px solid var(--tertiary-color)",
  },
  avatar: {
    width: "96px",
    height: "96px",
    borderRadius: "50%",
    background: "var(--secondary-color)",
    color: "var(--primary-color)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "36px",
    fontWeight: "bold",
  },
  userInfo: {
    textAlign: "center",
  },
  userName: {
    margin: "0",
    fontSize: "18px",
    fontWeight: "600",
    color: "var(--secondary-color)",
  },
  userRole: {
    fontSize: "14px",
    color: "var(--quaternary-color)",
    textTransform: "capitalize",
  },
  navigation: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  navButton: (active) => ({
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "12px 16px",
    border: "none",
    borderRadius: "8px",
    background: active ? "var(--tertiary-color)" : "transparent",
    color: active ? "var(--secondary-color)" : "var(--quaternary-color)",
    fontSize: "16px",
    fontWeight: "500",
    cursor: "pointer",
    transition: "all 0.2s ease",
    textAlign: "left",
    width: "100%",
  }),
  logoutButton: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "12px 16px",
    border: "none",
    borderRadius: "8px",
    background: "#fee2e2",
    color: "#ef4444",
    fontSize: "16px",
    fontWeight: "500",
    cursor: "pointer",
    transition: "all 0.2s ease",
    marginTop: "auto",
  },
  main: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  pageHeader: {
    marginBottom: "24px",
  },
  pageTitle: {
    margin: "0",
    fontSize: "24px",
    fontWeight: "bold",
    color: "var(--secondary-color)",
  },
  breadcrumb: {
    fontSize: "14px",
    color: "var(--quaternary-color)",
    margin: "4px 0 0 0",
  },
  contentCard: {
    background: "white",
    borderRadius: "16px",
    padding: "24px",
    boxShadow: "0 4px 6px -1px rgba(0,0,0,0.1)",
  },
  cardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "24px",
  },
  cardTitle: {
    margin: "0",
    fontSize: "18px",
    fontWeight: "600",
    color: "var(--secondary-color)",
  },
  editButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 16px",
    border: "none",
    borderRadius: "8px",
    background: "var(--tertiary-color)",
    color: "var(--secondary-color)",
    fontSize: "14px",
    fontWeight: "500",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  infoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: "24px",
  },
  infoItem: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  infoLabel: {
    fontSize: "14px",
    color: "var(--quaternary-color)",
    fontWeight: "500",
  },
  infoValue: {
    fontSize: "16px",
    color: "var(--secondary-color)",
    margin: "0",
  },
  certificatesGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))",
    gap: "24px",
  },
  certCard: {
    background: "white",
    borderRadius: "16px",
    padding: "24px",
    boxShadow: "0 4px 6px -1px rgba(0,0,0,0.1)",
  },
  certHeader: {
    marginBottom: "16px",
  },
  certBadge: (status) => ({
    display: "inline-block",
    padding: "4px 12px",
    borderRadius: "16px",
    fontSize: "12px",
    fontWeight: "500",
    background: status === "Valid" ? "#ecfdf5" : "#fee2e2",
    color: status === "Valid" ? "#059669" : "#ef4444",
    marginBottom: "8px",
  }),
  certTitle: {
    margin: "0",
    fontSize: "18px",
    fontWeight: "600",
    color: "var(--secondary-color)",
  },
  certDetails: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    marginBottom: "24px",
  },
  certInfo: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  certLabel: {
    fontSize: "14px",
    color: "var(--quaternary-color)",
  },
  certValue: {
    fontSize: "14px",
    color: "var(--secondary-color)",
    fontWeight: "500",
  },
  viewCertButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    width: "100%",
    padding: "12px",
    border: "none",
    borderRadius: "8px",
    background: "var(--tertiary-color)",
    color: "var(--secondary-color)",
    fontSize: "14px",
    fontWeight: "500",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: "rgba(0,0,0,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modalContent: {
    background: "white",
    borderRadius: "16px",
    width: "90%",
    maxWidth: "600px",
    maxHeight: "90vh",
    overflow: "auto",
  },
  modalHeader: {
    padding: "24px",
    borderBottom: "1px solid var(--tertiary-color)",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modalTitle: {
    margin: "0",
    fontSize: "20px",
    fontWeight: "600",
    color: "var(--secondary-color)",
  },
  modalClose: {
    border: "none",
    background: "none",
    fontSize: "24px",
    color: "var(--quaternary-color)",
    cursor: "pointer",
    padding: "4px",
  },
  modalBody: {
    padding: "24px",
  },
  certImage: {
    width: "100%",
    borderRadius: "8px",
  },
  modalFooter: {
    padding: "24px",
    borderTop: "1px solid var(--tertiary-color)",
    display: "flex",
    justifyContent: "flex-end",
  },
  downloadButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 24px",
    border: "none",
    borderRadius: "8px",
    background: "var(--secondary-color)",
    color: "white",
    fontSize: "14px",
    fontWeight: "500",
    cursor: "pointer",
    textDecoration: "none",
    transition: "all 0.2s ease",
  },
  buttonIcon: {
    fontSize: "16px",
  },
};

export default styles;